package com.bs;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.12 at 03:42:16 下午 CST 
//


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 税务行政许可最高限额申请审批VO
 * 
 * <p>Java class for FPSwxzxkZgxeSqspVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FPSwxzxkZgxeSqspVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sjgsdq" type="{http://www.chinatax.gov.cn/dataspec/}sjgsdq"/>
 *         &lt;element name="fpzlDm" type="{http://www.chinatax.gov.cn/dataspec/}fpzlDm"/>
 *         &lt;element name="djxh" type="{http://www.chinatax.gov.cn/dataspec/}djxh"/>
 *         &lt;element name="scrDm" type="{http://www.chinatax.gov.cn/dataspec/}scrDm"/>
 *         &lt;element name="hdslid" type="{http://www.chinatax.gov.cn/dataspec/}hdslid"/>
 *         &lt;element name="scrq" type="{http://www.chinatax.gov.cn/dataspec/}scrq"/>
 *         &lt;element name="lcslid" type="{http://www.chinatax.gov.cn/dataspec/}lcslid"/>
 *         &lt;element name="xkyxqz" type="{http://www.chinatax.gov.cn/dataspec/}xkyxqz"/>
 *         &lt;element name="scjgscyjDm" type="{http://www.chinatax.gov.cn/dataspec/}scjgscyjDm"/>
 *         &lt;element name="fpzgkpxeDm" type="{http://www.chinatax.gov.cn/dataspec/}fpzgkpxeDm"/>
 *         &lt;element name="kpxesqspuuid" type="{http://www.chinatax.gov.cn/dataspec/}kpxesqspuuid"/>
 *         &lt;element name="scswjgDm" type="{http://www.chinatax.gov.cn/dataspec/}scswjgDm"/>
 *         &lt;element name="xkyxqq" type="{http://www.chinatax.gov.cn/dataspec/}xkyxqq"/>
 *         &lt;element name="lrrDm" type="{http://www.chinatax.gov.cn/dataspec/}lrrDm"/>
 *         &lt;element name="scjgscyjsm" type="{http://www.chinatax.gov.cn/dataspec/}scjgscyjsm"/>
 *         &lt;element name="sqly" type="{http://www.chinatax.gov.cn/dataspec/}sqly"/>
 *         &lt;element name="xgrDm" type="{http://www.chinatax.gov.cn/dataspec/}xgrDm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FPSwxzxkZgxeSqspVO", propOrder = {
    "sjgsdq",
    "fpzlDm",
    "djxh",
    "scrDm",
    "hdslid",
    "scrq",
    "lcslid",
    "xkyxqz",
    "scjgscyjDm",
    "fpzgkpxeDm",
    "kpxesqspuuid",
    "scswjgDm",
    "xkyxqq",
    "lrrDm",
    "scjgscyjsm",
    "sqly",
    "xgrDm"
})
public class FPSwxzxkZgxeSqspVO {

    @XmlElement(required = true, nillable = true)
    protected String sjgsdq;
    @XmlElement(required = true, nillable = true)
    protected String fpzlDm;
    @XmlElement(required = true, nillable = true)
    protected String djxh;
    @XmlElement(required = true, nillable = true)
    protected String scrDm;
    @XmlElement(required = true, nillable = true)
    protected String hdslid;
    @XmlElement(required = true, nillable = true)
    protected String scrq;
    @XmlElement(required = true, nillable = true)
    protected String lcslid;
    @XmlElement(required = true, nillable = true)
    protected String xkyxqz;
    @XmlElement(required = true, nillable = true)
    protected String scjgscyjDm;
    @XmlElement(required = true, nillable = true)
    protected String fpzgkpxeDm;
    @XmlElement(required = true, nillable = true)
    protected String kpxesqspuuid;
    @XmlElement(required = true, nillable = true)
    protected String scswjgDm;
    @XmlElement(required = true, nillable = true)
    protected String xkyxqq;
    @XmlElement(required = true, nillable = true)
    protected String lrrDm;
    @XmlElement(required = true, nillable = true)
    protected String scjgscyjsm;
    @XmlElement(required = true, nillable = true)
    protected String sqly;
    @XmlElement(required = true, nillable = true)
    protected String xgrDm;

    /**
     * Gets the value of the sjgsdq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSjgsdq() {
        return sjgsdq;
    }

    /**
     * Sets the value of the sjgsdq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSjgsdq(String value) {
        this.sjgsdq = value;
    }

    /**
     * Gets the value of the fpzlDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzlDm() {
        return fpzlDm;
    }

    /**
     * Sets the value of the fpzlDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzlDm(String value) {
        this.fpzlDm = value;
    }

    /**
     * Gets the value of the djxh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDjxh() {
        return djxh;
    }

    /**
     * Sets the value of the djxh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDjxh(String value) {
        this.djxh = value;
    }

    /**
     * Gets the value of the scrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrDm() {
        return scrDm;
    }

    /**
     * Sets the value of the scrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrDm(String value) {
        this.scrDm = value;
    }

    /**
     * Gets the value of the hdslid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdslid() {
        return hdslid;
    }

    /**
     * Sets the value of the hdslid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdslid(String value) {
        this.hdslid = value;
    }

    /**
     * Gets the value of the scrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrq() {
        return scrq;
    }

    /**
     * Sets the value of the scrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrq(String value) {
        this.scrq = value;
    }

    /**
     * Gets the value of the lcslid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLcslid() {
        return lcslid;
    }

    /**
     * Sets the value of the lcslid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLcslid(String value) {
        this.lcslid = value;
    }

    /**
     * Gets the value of the xkyxqz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXkyxqz() {
        return xkyxqz;
    }

    /**
     * Sets the value of the xkyxqz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXkyxqz(String value) {
        this.xkyxqz = value;
    }

    /**
     * Gets the value of the scjgscyjDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScjgscyjDm() {
        return scjgscyjDm;
    }

    /**
     * Sets the value of the scjgscyjDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScjgscyjDm(String value) {
        this.scjgscyjDm = value;
    }

    /**
     * Gets the value of the fpzgkpxeDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFpzgkpxeDm() {
        return fpzgkpxeDm;
    }

    /**
     * Sets the value of the fpzgkpxeDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFpzgkpxeDm(String value) {
        this.fpzgkpxeDm = value;
    }

    /**
     * Gets the value of the kpxesqspuuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKpxesqspuuid() {
        return kpxesqspuuid;
    }

    /**
     * Sets the value of the kpxesqspuuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKpxesqspuuid(String value) {
        this.kpxesqspuuid = value;
    }

    /**
     * Gets the value of the scswjgDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScswjgDm() {
        return scswjgDm;
    }

    /**
     * Sets the value of the scswjgDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScswjgDm(String value) {
        this.scswjgDm = value;
    }

    /**
     * Gets the value of the xkyxqq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXkyxqq() {
        return xkyxqq;
    }

    /**
     * Sets the value of the xkyxqq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXkyxqq(String value) {
        this.xkyxqq = value;
    }

    /**
     * Gets the value of the lrrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLrrDm() {
        return lrrDm;
    }

    /**
     * Sets the value of the lrrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLrrDm(String value) {
        this.lrrDm = value;
    }

    /**
     * Gets the value of the scjgscyjsm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScjgscyjsm() {
        return scjgscyjsm;
    }

    /**
     * Sets the value of the scjgscyjsm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScjgscyjsm(String value) {
        this.scjgscyjsm = value;
    }

    /**
     * Gets the value of the sqly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSqly() {
        return sqly;
    }

    /**
     * Sets the value of the sqly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSqly(String value) {
        this.sqly = value;
    }

    /**
     * Gets the value of the xgrDm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXgrDm() {
        return xgrDm;
    }

    /**
     * Sets the value of the xgrDm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXgrDm(String value) {
        this.xgrDm = value;
    }

}
