debug: true
server:
  servlet:
    context-path: /Trysb
    session:
      timeout: 60
  port: 8081

spring:
  application:
    name: tryboot-service
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    cache: true

  datasource:
    data-password: 123456
    data-username: root
    url: jdbc:mysql://localhost:3306/jeecg-boot?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/trysb/dao/xml/*.xml
